### ISSUE TITLE
Add docker build

### ISSUE THREAD

**Issue by yatharthranjan** [RADAR-base/RADAR-HDFS-Sink-Connector#8]
Create a Dockerfile and use it to build the connector image instead of RADAR-Docker. Also so that the automatic builds can be configured based on releases.

**Comment by blootsvoets** [comment]
If possible, I’d prefer to use the plain Mongodb-Sink-Connector directly in radar docker , instead of this custom connector.

**Comment by yatharthranjan** [comment]
Cool. I will move this issue to the plain connector then. Also whats the main difference between the two ?

**Comment by yatharthranjan** [comment]
closed in #11, will be available in the next release
